### ISSUE TITLE
Add Jira-/Confluence-Log to IntelliJ run configs

### ISSUE THREAD

**Issue by sjahreis** [linked-planet/atlassian-plugin-kotlin#11]
**Describe the solution you'd like**
View log streams of Jira / Confluence in IntelliJ.

**Fix**
Add an additional `log_file` entries in IntelliJ to run and debug configurations. E.g. `<log_file alias="Jira-Log" path="$PROJECT_DIR$/target/jira/home/log/atlassian-jira.log" />` in `jira_debug.run.xml`.

**Comment by weickmanna** [comment]
@sjahreis done

**Comment by sjahreis** [comment]
LGTM (Confluence seems to have no such log file...)
