### ISSUE TITLE
Prevent settings.xml override

### ISSUE THREAD

**Issue by sjahreis** [linked-planet/atlassian-plugin-kotlin#4]
**Is your feature request related to a problem? Please describe.**
The repository can be built without `atlas-mvn` using the `atlassian-public` repository as mirror for `central` to collect the dependencies. Currently the repository contains a `.mvn/local-setttings.xml` which is configured as the default user settings file for Maven within this project using the `.mvn/maven.conf` file. To compile the project in IntelliJ successfully, the Maven user settings file has to be changed to the `.mvn/maven.conf` file as well.

But afterwards settings (e.g. credentials for repositories) within the user's custom settings file `~/.m2/settings.xml` aren't applied anymore.

Furthermore IntelliJ doesn't consider the file `maven.conf` (see bug https://youtrack.jetbrains.com/issue/IDEA-197658) which requires the manual change of the user settings file within the IDE.

**Describe the solution you'd like**
The settings in the user's custom settings file `~/.m2/settings.xml` are merged with the mirror settings of the file `.mvn/local-setttings.xml`. Therewith the project is buildable out-of-the-box via the Maven CLI and IntelliJ. There are no manual changes required anymore.

**Describe alternatives you've considered**
- append a custom profile `atlassian-central-profile` defining the required mirror
  - Problem: IntelliJ doesn't consider mirrors within profiles (see bug https://youtrack.jetbrains.com/issue/IDEA-91662) -> Project can't be built
- multiple user settings files via the CLI or `maven.conf` file
  - Problem: not supported by Maven
- use a Maven extension (see https://github.com/gzm55/project-settings-maven-extension) which merges multiple user settings files
  - Problem: IntelliJ doesn't consider values of this extension -> Project can't be built

**Additional context**
None

**Comment by weickmanna** [comment]
According to the YouTrack issue tracker, IntelliJ plans to support maven.conf files starting from 2021.3. So maybe we can actually fix this sometime soon!

**Comment by sjahreis** [comment]
IntelliJ 2021.3 is released and supports `maven.conf` files now. See https://www.jetbrains.com/de-de/idea/whatsnew/#build-tools.

**Comment by weickmanna** [comment]
@sjahreis is this issue fully solved by now?
I don't have any problems with this anymore in my projects, so from my point of view we could close this ...

**Comment by sjahreis** [comment]
LGTM
