### ISSUE TITLE
Proper install documentation

### ISSUE THREAD

**Issue by Aleksnako** [linked-planet/atlassian-plugin-kotlin#7]
I would love to have a detailed instructions to make it work out of the box. 

Right now I have my folder tree created, fixed some dependencies that didnt work out of the box in the backend but still unable to enable the plugin. 

I cannot build the frontend because there are some missing classes and warnings.

**Comment by p-louis** [comment]
Hey @Aleksnako, 

Could you provide us with some additional information on what classes are missing/ what warnings you're getting?

Could it be that the artifact-id you chose contains any dashes? If so, the frontend-package-names will also contain these dashes, making them invalid. The same is true for some generated function names in the frontend.

**Comment by weickmanna** [comment]
@Aleksnako I agree such a step by step instruction is very much needed.

As @p-louis mentioned, we have a known issue with generation of frontend classes when there are dashes in the artifact-id. But for these you should be able to easily see and fix the compile errors.

For it to work it also highly depends on your local setup. For example, it is important that you are building with Java 8. I think we are mostly building locally with Java 11 but anything above that will probably not work. Also, the backend dependencies need the Atlassian repo. There is this file, which should have been generated into your project as well:
https://github.com/linked-planet/atlassian-plugin-kotlin/blob/master/src/main/resources/archetype-resources/.mvn/local-settings.xml

However, this file is not picked up by IntelliJ. So as a first step, you always try to build with JDK 8 & mvn command line if anything does not work. When trying to enable the plugin, what errors does it produce in the log file (target/jira/home/log/atlassian-jira.log)?

Regarding the frontend, try to build the frontend via command line. What errors do you get?
```
cd frontend
./gradlew clean build
```

**Comment by Aleksnako** [comment]
@p-louis @weickmanna 

Thank you very much for the fast responses, I'm gonna try to describe the problem as detailed as i can:

First, i have some dependencies unresolved by maven (using "atlas-package" from terminal), but as you said this was a problem with the setting.xml file in Intellij. 
After resolving that, I still had some unresolved dependencies, I had to add them manually into the pom in the dependencies part:


        <dependency>
            <groupId>org.jetbrains.dokka</groupId>
            <artifactId>dokka-maven-plugin</artifactId>
            <version>1.5.31</version>
        </dependency>
        <dependency>
            <groupId>com.coderplus.maven.plugins</groupId>
            <artifactId>copy-rename-maven-plugin</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>3.0.0</version>
        </dependency>

Then, I had an issue with "banned dependencies", I dont fully understand why does this, because I spect that if the "scope" from 


           <groupId>com.atlassian.jira</groupId>
           <artifactId>jira-api</artifactId>
           <version>${jira.version}</version>
            <scope>provided</scope>

is "provided" it should extend to all dependat classes, but in my case it doesent so i had to add this dependencies:


        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>26.0-jre</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.30</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.8.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.9</version>
            <scope>provided</scope>
        </dependency>

After all that, I added this part (extractDependencies to false)to avoid some extra warnings in the compilation:


            <plugin>
                <groupId>com.atlassian.maven.plugins</groupId>
                <artifactId>jira-maven-plugin</artifactId>
                <version>${amps.version}</version>
                <extensions>true</extensions>
                <configuration>
                    [...]
                    <extractDependencies>false</extractDependencies>
                </configuration>
            </plugin>

At this point I did finally load Jira locally without errors, but when I went to Application Manager, the plugin didnt load (greyed out and unable to "Enable").
I had this problem in the past, and just adding this:


            <Import-Package>
                 *;version="0";resolution:="optional",
            </Import-Package>

at "com.atlassian.maven.plugins" plugin section, I finally had the plugin enabled.

After that (or in between I cant remember) I had to fix some imports in the "src/main/kotlin/exampleApp/app/TempoCalendarAppApplication.kt" in the frontend, because they were referencing some classes with the wrong name

`import tempoCalendarApp.page.exampleAppMainPage
import tempoCalendarApp.reducer.ExampleAppHandler`

and change them with the actual classes generated with my configuration (This time, Intellij did all the work for me)

Finally I have a fully functional plugin, but I still dont understand how to pass data to the frontend from the backend, but I guess It's matter of time to figure it out.

Thank you for your time!

**Comment by p-louis** [comment]
> Finally I have a fully functional plugin, but I still dont understand how to pass data to the frontend from the backend, but I guess It's matter of time to figure it out.

Passing data to the frontend can be achieved in two general ways: 
  * REST-Endpoints: Exactly what you'd expect, you can create rest-endpoints inside the Jira plugin to provide data/interactions for the frontend.
  * Velocity-Context: If you need to initialize your app-component with some values, these can also be passed in through the velocity-context. When you're calling your app-component ([module_jira.vm : Line 23](https://github.com/linked-planet/atlassian-plugin-kotlin/blob/master/src/main/resources/archetype-resources/src/main/resources/templates/action/module_jira.vm)), you can pass in additional parameters that may be provided from the velocity-context.

**Comment by weickmanna** [comment]
@Aleksnako regarding the backend dependencies, it should definitely work out of the box without all these adaptions. This is proven by the GitHub Actions pipeline: it initializes a new project on a fresh Ubuntu container and then runs some Selenium tests on the generated project, which is fully started within a Jira container.

We moved away from the atlas-mvn command line tools as they add various things to the build process that are not quite transparent. We build using regular Maven and simply make use of the Atlassian Maven Plugins, as you can simply do mvn jira:debug just as well. This should only need the dependency mirror defined in the local-settings.xml and then it should work out of the box.

Whenever new dependencies are added the plugins potentially break due to the transitive dependencies. Due to the way this Atlassian Spring Scanner works it wants to have all these dependency libraries present even when the pom.xml of the library declares them as optional. These are fixed as you did with the ImportPackage statement. However, if you initialize a fresh project using this template, none of this should be necessary.

Some dependencies might only be resolved when the ci Maven profile is added, as in mvn package -Pci. We have this separate profile to do some additional work like generating documentation only in the CI pipeline. But if you never run it with the profile locally, it won't know about these dependencies locally. So you can resolve them by just building once with the profile locally.

**Comment by weickmanna** [comment]
Closing this.
@Aleksnako feel free to reach out to us if you need any more help.
