### ISSUE TITLE
github actions with ubuntu-latest incompatible with sass-loader

### ISSUE THREAD

**Issue by betacore** [linked-planet/atlassian-plugin-kotlin#8]
**Describe the bug**
github actions uses the version 6 of nodejs which makes the sass-loader and node-sass incompatible with the build
environment.

**To Reproduce**
1. clean and build frontend via github actions
2. build fails because of incompatible versions

**Expected behavior**
The build on github should run as expected

**Additional context**
Update sass-loader to 10.2.0
Update node-sass to 6.0.1

**Comment by weickmanna** [comment]
@betacore build is now running in GitHub actions and sass-loader, node-sass are used from ui-kit-lib.

**Comment by sjahreis** [comment]
LGTM
